paths:
  static: public
  uploads: public/uploads
timezone: Asia/Jakarta
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  blog:
    path: src/content/blog
    icon: event_available
  config:
    path: src/config
    icon: coffee
  content_pages:
    path: src/content/pages
    icon: contact_page
  lib:
    path: src/lib
    icon: adb
  project:
    path: src/content/project
    icon: eject
